- name: demo on vars_files
  hosts: local
  connection: local
  vars_files:             #	→ they will refer to the course.yaml file, fetch the vars. 
  - course.yaml
  tasks:
  - name: print variables information
    debug:
      msg: "Hi, {{ Learner }} is learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"
