- name: demo on inventory variables
  hosts: local
  connection: local # frontend
  tasks:
  - name: print information
    debug:
      msg: "Hi, {{ Learner }} is learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"