[frontend]
172.31.42.20  #COURSE="Ansible for NODE-1"
172.31.39.230 #COURSE="Ansible for NODE-2"


[catalogue]
172.31.17.74
[mongodb]
172.31.17.75
[redi]
172.31.17.76
[mysql]
172.31.17.77
[rabbimq]
172.31.17.78
; group of groups
[roboshop:children]
frontend
catalogue
user
cart

[local]
localhost

;local group vars
;  [local:vars]
;  COURSE="Ansible"
;  TRAINER="Sivakumar"
;  Learner="Subbu"
;  DURATION="10HRS"

; [frontend:vars]
;  COURSE="Ansible"
;  TRAINER="Sivakumar"
;  Learner="Subbu"
;  DURATION="10HRS"
